#!/usr/bin/perl
use strict;
use warnings;

my @fatals = qw(
BAD_LOCUS_TAG_FORMAT
DISC_BACTERIA_SHOULD_NOT_HAVE_MRNA
DISC_CITSUBAFFIL_CONFLICT
DISC_INCONSISTENT_MOLTYPES
DISC_MAP_CHROMOSOME_CONFLICT
DISC_MICROSATELLITE_REPEAT_TYPE
DISC_MISSING_AFFIL
DISC_NONWGS_SETS_PRESENT
DISC_QUALITY_SCORES
DISC_RBS_WITHOUT_GENE
DISC_SHORT_RRNA
DISC_SEGSETS_PRESENT
DISC_SOURCE_QUALS_ASNDISC
DISC_SUBMITBLOCK_CONFLICT
DISC_SUSPECT_RRNA_PRODUCTS
DISC_TITLE_AUTHOR_CONFLICT
DISC_UNPUB_PUB_WITHOUT_TITLE
DISC_USA_STATE
EC_NUMBER_ON_UNKNOWN_PROTEIN
INCONSISTENT_LOCUS_TAG_PREFIX
INCONSISTENT_PROTEIN_ID
MISSING_GENES
MISSING_LOCUS_TAGS
MISSING_PROTEIN_ID
ONCALLER_ORDERED_LOCATION
PARTIAL_CDS_COMPLETE_SEQUENCE
PSEUDO_MISMATCH
RNA_CDS_OVERLAP
RNA_NO_PRODUCT
SHOW_HYPOTHETICAL_CDS_HAVING_GENE_NAME
SUSPECT_PRODUCT_NAMES
TEST_OVERLAPPING_RRNAS
DISC_BACTERIAL_PARTIAL_NONEXTENDABLE_PROBLEMS
MISSING_GENOMEASSEMBLY_COMMENTS
);

while(<>) {
	for my $fatal ( @fatals ) {
		print "FATAL: ", $_ if /$fatal/;
	}
}
