#!/usr/bin/perl

=pod

=head1 NAME

wgs2ncbi - prepares whole genome sequencing projects for submission to NCBI

=head1 SYNOPSIS

 Usage: wgs2ncbi [action] -conf [config file]

=head1 DESCRIPTION

C<wgs2ncbi> is a utility that provides the functionality for preparing submissions of 
annotated, whole genomes to NCBI. It does this by performing a number of actions. Each
of these actions need to be invoked as a subcommand, which will then run for a certain 
time. Here follows a brief description of the actions:

=head2 C<prepare>

Prepares the rest of the procedure by expanding the single genome annotation file into 
separate files, one for each contig.

=head2 C<process>

Processes the genome by writing out feature tables and masking contig segments as needed.

=head2 C<convert>

Converts the masked contigs and feature tables into ASN.1 using tbl2asn.

=head2 C<compress>

Packs the ASN.1 files into a .tar.gz archive for upload to NCBI.

=cut


BEGIN {
	use FindBin '$Bin';
	use lib "$Bin/../lib";
}
use Bio::WGS2NCBI;
my $action = shift;
if ( $action and Bio::WGS2NCBI->can($action) ) {
    Bio::WGS2NCBI->$action;
    exit 0;
}
Bio::WGS2NCBI->help;